# Site settings
title: "Shaheim 0.H"
description: "Hi my name is Shaheim Ogbomo-Harmitt, welcome to my website."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shaheim Ogbomo-Harmitt"
resume_title:                   "Biomedical Engineering and Imaging Sciences PhD Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "Shaheim@hotmail.co.uk"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Shaheim Ogbomo-Harmitt received his BEng in Biomedical Engineering and MRes in Biomedical and Translation Sciences at King's College London (KCL). During his studies at KCL, Shaheim completed research projects on applying machine learning to perinatal neuroimaging for biomarker discovery and investigating the instability of Turing patterns on complex networks by analysing the eigenvalue distribution of the Laplacian matrix. Currently, Shaheim is a PhD student at KCL, undertaking research in combining image-based computational biophysical modelling with deep learning to optimise ablation therapy for Atrial Fibrillation under the supervision of Dr Oleg Aslanidi and Dr Andrew King.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
